


#include "servo.h"
#include "gpio.h"


static bool timer1_pwmMode_init(const TIMER_CHANNEL);



static bool timer1_pwmMode_init(const TIMER_CHANNEL TIMER_CHAN)
{

	TIMER1_COUNT_REGISTER=TIMER_1_CLEAR_MASK;
	TIMER1_INPUT_CAPTURE_REGISTER=SERVO_TOP_VALUE_ICR1_FCPU_8MHZ_WITH_PRESCALAR_64;

	if(TIMER_CHAN==_CHANNEL_A)
	{
		TIMER1A_COMPARE_REGISTER=SERVO_COMPARE_VALUE_RELATIVE_TO_ZERO_POSTION;
		TIMER1A_CONTROL_REGISTER|=TIMER_1_PWM_NON_INVERTING_OC1A_MASK;

	}
	else
	{
		TIMER1B_COMPARE_REGISTER=SERVO_COMPARE_VALUE_RELATIVE_TO_ZERO_POSTION;
		TIMER1A_CONTROL_REGISTER|=TIMER_1_PWM_NON_INVERTING_OC1B_MASK;
	}

	TIMER1A_CONTROL_REGISTER|=TIMER_1_FAST_PWM_MASK;
	TIMER1B_CONTROL_REGISTER|=TIMER_1_PWM_F_CPU_64_MASK;

	return TRUE;

}

