

#include "watchdog.h"




void WATCHDOG_init(const WATCHDOG_PRESCALAR PRESCALAR_VALUE)
{
	WATCHDOG_TIMER_CONTROL_REGISTER = ((WATCHDOG_TIMER_CONTROL_REGISTER & 0XF8) | (PRESCALAR_VALUE));
}



void WATCHDOG_enable()
{
	SET_BIT(WATCHDOG_TIMER_CONTROL_REGISTER,BIT_3);
}



void WATCHDOG_disable()
{
	WATCHDOG_TIMER_CONTROL_REGISTER|=(1<<BIT_4)|(1<<BIT_3);
	RESET_BIT(WATCHDOG_TIMER_CONTROL_REGISTER,BIT_3);
}
